name: chat_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"
dependencies:
  firebase_auth: ^3.3.4
  firebase_core: ^1.10.6
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  cloud_firestore: ^3.1.5
  cupertino_icons: ^1.0.2
  dio: ^4.0.0
  flutter_bloc: ^8.0.1
  easy_localization: ^3.0.0
  connectivity_plus: ^2.0.2
  font_awesome_flutter: ^9.1.0
  fluttertoast: ^8.0.8
  get_storage: ^2.0.3
  nil: ^1.1.1

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  flutter_app_name: ^0.1.1
  flutter_native_splash: ^1.3.2
  flutter_launcher_icons: ^0.9.2
  #TODO: run these commands
  #flutter pub run flutter_app_name
  #flutter pub run flutter_native_splash:create
  #flutter pub run flutter_launcher_icons:main
flutter_app_name:
  name: "Chat App"


flutter_native_splash:
  color: "#F5FCF9"
  image:  assets/images/logo.png
  color_dark: "#1D1D35"
  image_dark: assets/images/logo.png
  android: true
  ios: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/chat_app_icon.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/translation/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter.ttf
